name: A curated list of awesome Livepeer resources.
title: null
markdown: GFM
google_analytics: 
# NOTE: Remove items below when https://github.com/pages-themes/primer/pull/85 is merged.
plugins:  
  - jekyll-remote-theme
remote_theme: rickstaa/primer@make_footer_customisable
